"""
State schema for CMN-C1-042 — Sales Call & Meeting Debrief Summary Agent.

All state fields are primitives (str, bool, int) as required by:
- the framework contract (state safety rules)
- the security rules (Rule 1.1 — msgpack checkpoint safety)

Prohibited in state: Pydantic BaseModel, dataclass, datetime, bytes, credentials,
dict[str, Any] (use JSON str instead), InvocationContext (travels via config only).

See ADR-004 for the rationale behind crm_fields: str (not dict).
"""

from __future__ import annotations


from framework.schemas.agent_state import AgentState


class DebriefState(AgentState):  # type: ignore[misc]
    """Flat TypedDict for CMN-C1-042 pipeline state.

    All fields are primitives (str, bool, int) for msgpack checkpoint safety.
    No Pydantic models, dataclasses, datetime objects, or bytes permitted.
    """

    # ── Input ────────────────────────────────────────────────────────────────
    raw_transcript: str  # Raw meeting transcript (text only, max 50,000 chars)
    session_id: str  # Trace correlation ID (UUID, generated at entry)

    # ── Pre-process intermediates ─────────────────────────────────────────────
    cleaned_transcript: str  # Normalised transcript (aizuchi removed, speakers tagged)
    annotated_transcript: str  # cleaned_transcript + nuance annotations injected
    pii_masked: bool  # True if S-2 masked >= 1 PII token
    pii_mask_count: int  # Count of PII tokens masked (audit, S-4)

    # ── Main output (primitives only — DebriefOutput unpacked here) ───────────
    summary: str  # Structured meeting summary
    cannot_summarize: bool
    #: The language the debrief is written in -- "en", "ja", or "" when nothing could be
    #: read. Declared here because LangGraph drops any key the schema does not name, and
    #: it does so silently: the renderer kept printing English headings above a Japanese
    #: debrief with no error anywhere (measured 2026-08-28).
    output_language: str  # True when no LLM available (fail-closed empty advisory)
    crm_fields: str  # JSON str — CRM field values (msgpack-safe dict->str)
    email_draft: str  # Follow-up email draft (subject + body)

    # ── Post-process intermediates ────────────────────────────────────────────
    crm_validated: bool  # True if crm_fields passed CRM JSON Schema validation
    crm_validation_errors: str  # JSON str — list of validation error messages (empty="")
    output_json: str  # Final formatted output JSON str

    # ── Error handling ────────────────────────────────────────────────────────
    error: str  # JSON str — {"code": str, "attempt": int} | ""
    retry_count: int  # LLM retry counter (reset per invocation)

    # ── Audit / trace (S-4) ──────────────────────────────────────────────────
    invocation_id: str  # UUID per invocation
    audit_input_hash: str  # SHA-256 of PII-masked raw_transcript (APPI-safe; no raw PII in hash)
    audit_output_hash: str  # SHA-256 of output_json (no content in log)


def initial_state(raw_transcript: str, session_id: str) -> DebriefState:
    """Factory for a fully-initialized DebriefState.

    All fields explicitly set to safe empty defaults.
    Callers MUST use this factory — never build the dict manually.

    Args:
        raw_transcript: Raw meeting transcript text (max 50,000 chars).
        session_id: Trace correlation ID (UUID string, generated by caller).

    Returns:
        DebriefState with all 17 fields initialized to type-safe defaults.
    """
    return DebriefState(
        raw_transcript=raw_transcript,
        session_id=session_id,
        cleaned_transcript="",
        annotated_transcript="",
        pii_masked=False,
        pii_mask_count=0,
        summary="",
        cannot_summarize=False,
        crm_fields="{}",
        email_draft="",
        crm_validated=False,
        crm_validation_errors="",
        output_json="",
        error="",
        retry_count=0,
        invocation_id="",  # populated by TranscriptCleanNode
        audit_input_hash="",  # populated by TranscriptCleanNode
        audit_output_hash="",  # populated by OutputFormatNode
    )
